// Downloads Vazirmatn + Inter woff2 files from Google Fonts and emits a
// self-hosted @font-face stylesheet. Nothing hits Google at runtime.
//
//   node tools/fonts/fetch-fonts.js
//
// Google serves per-subset woff2 slices with matching unicode-range rules, so the
// files we cache ARE the subsets — no local subsetting toolchain needed.

const fs = require('fs')
const path = require('path')

const OUT_DIR = path.join(__dirname, '..', '..', 'public', 'fonts')
const CSS_OUT = path.join(__dirname, '..', '..', 'app', 'fonts.css')

// A modern UA is what makes the API return woff2 + unicode-range.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

// Both families ship as variable fonts on Google Fonts: one woff2 per subset carries
// every weight. Requesting a range (not a list) makes that explicit, and each face is
// declared once with a font-weight RANGE. Declaring the same file three times with
// fixed weights would pin the browser to a single instance and defeat the variable axis.
const FAMILIES = [
  { name: 'Vazirmatn', spec: 'Vazirmatn:wght@100..900', keep: ['arabic', 'latin'], range: '100 900' },
  { name: 'Inter', spec: 'Inter:wght@100..900', keep: ['latin'], range: '100 900' },
]

async function getCss(spec) {
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`CSS fetch failed for ${spec}: ${res.status}`)
  return res.text()
}

async function download(url, dest) {
  if (fs.existsSync(dest)) return fs.statSync(dest).size
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`font fetch failed: ${url} -> ${res.status}`)
  const buf = Buffer.from(await res.arrayBuffer())
  fs.writeFileSync(dest, buf)
  return buf.length
}

;(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true })
  const blocks = []
  const seen = new Set()
  let total = 0

  for (const fam of FAMILIES) {
    const css = await getCss(fam.spec)

    // Google emits "/* arabic */" style comments before each @font-face.
    const chunks = css.split('/*').slice(1)
    for (const chunk of chunks) {
      const subset = chunk.slice(0, chunk.indexOf('*/')).trim()
      if (!fam.keep.includes(subset)) continue

      const body = chunk.slice(chunk.indexOf('*/') + 2)
      const url = body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1]
      const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]
      if (!url || !range) continue

      const file = `${fam.name.toLowerCase()}-${subset}.woff2`
      if (seen.has(file)) continue
      seen.add(file)

      const size = await download(url, path.join(OUT_DIR, file))
      total += size
      console.log(`  ${file.padEnd(30)} ${(size / 1024).toFixed(1)} KB  (weights ${fam.range})`)

      blocks.push(
        `@font-face {\n` +
          `  font-family: '${fam.name}';\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${fam.range};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${file}') format('woff2');\n` +
          `  unicode-range: ${range};\n` +
          `}`
      )
    }
  }

  const header =
    `/* GENERATED by tools/fonts/fetch-fonts.js — do not edit by hand.\n` +
    `   Self-hosted: no request leaves for Google at runtime. */\n\n`
  fs.writeFileSync(CSS_OUT, header + blocks.join('\n\n') + '\n')
  console.log(`\n${blocks.length} faces, ${(total / 1024).toFixed(0)} KB total -> app/fonts.css`)
})().catch((err) => {
  console.error(err.message)
  process.exit(1)
})
